apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cms-consistency
spec:
  releaseName: consistency
  chart:
    spec:
      chart: rucio-consistency
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: cms-rucio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-consistency
    - kind: ConfigMap
      name: instance-consistency
    - kind: ConfigMap
      name: instance-consistency-jobs
