apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-probes-crontab
spec:
  releaseName: probes-crontab
  chart:
    spec:
      chart: charts/rucio-probes
      version: "<38.0"
      sourceRef:
        kind: GitRepository
        name: probes-crontab
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-rucio-common
    - kind: ConfigMap
      name: instance-rucio-release
    - kind: ConfigMap
      name: cms-rucio-probes
    - kind: ConfigMap
      name: instance-rucio-probes
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default
