apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loadtest
spec:
  releaseName: loadtest
  chart:
    spec:
      chart: rucio-loadtest
      sourceRef:
        kind: HelmRepository
        name: cms-rucio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: instance-loadtest
