apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loadtest-daemons
spec:
  releaseName: loadtest-daemons
  chart:
    spec:
      chart: rucio-daemons
      version: "<37.0"
      sourceRef:
        kind: HelmRepository
        name: rucio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-rucio-common
    - kind: ConfigMap
      name: cms-rucio-daemons
    - kind: ConfigMap
      name: instance-rucio-daemons
    - kind: ConfigMap
      name: instance-rucio-release
    - kind: ConfigMap
      name: loadtest-rucio-daemons
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default
