apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rucio-decommissioner-git
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/juanpablosalas/helm-charts.git
  ref:
    branch: rsedecommissioner-daemon
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/helm/