# More reapers (or threads) than this cause issues for CERN Oracle, so use only temporarily. Reducing the sleep time is similar
reaperCount: 0
judgeInjectorCount: 0
judgeRepairerCount: 0
conveyorTransferSubmitterCount: 0
conveyorPollerCount: 0
conveyorReceiverCount: 0
conveyorFinisherCount: 0
conveyorThrottlerCount: 0

judgeEvaluatorCount: 0
tracerKronosCount: 0
judgeCleanerCount: 0
replicaRecovererCount: 0
minosTemporaryExpirationCount: 0

replicaRecoverer:
  activeMode: true
  limitSuspiciousFilesOnRse: 500
  secretMounts:
    - secretFullName: replica-recoverer-config
      mountPath: /opt/rucio/etc/suspicious_replica_recoverer.json
      subPath: suspicious_replica_recoverer.json
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 400Mi

reaper:
  threads: 4
  includeRses: "reaper=True\\rse_type=TAPE\\tier=1\\tier=0\\T2_CH_CERN"
  chunkSize: 4000
  sleepTime: 120

conveyorPoller:
  threads: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1000Mi
    requests:
      cpu: 750m
      memory: 400Mi

conveyorTransferSubmitter:
  groupBulk: 200
  bulk: 400
  sleepTime: 60
  threads: 5
  sourceStrategy: throughput

judgeEvaluator:
  threads: 8
  didLimit: 1000
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 200Mi

judgeRepairer:
  threads: 2
judgeInjector:
  threads: 3

conveyorFinisher:
  threads: 5
  resources:
    limits:
      memory: 8000Mi
    requests:
      memory: 600Mi

podLabels:
  rucioInstance: "prod"

transmogrifier:
  threads: 8
  sleepTime: 30
  bulk: 400

tracerKronos:
  threads: 2
  sleepTimeFiles: 120
  sleepTimeDatasets: 30

config:
  common:
    loglevel: "INFO"
  messaging_hermes:
    port: "61313"
    nonssl_port: "61313"
  tracer_kronos:
    chunksize: "5"
    prefetch_size: "5"
