consistency:
  ignore:
    - /store/backfill
    - /store/test
    - /store/unmerged
    - /store/temp
    - /store/mc/SAM
    - /store/mc/HC
    - /store/accounting
    - /store/express/tier0_harvest
  sites:
    T1_DE_KIT_Disk:
      interval: 7
    T1_DE_KIT_Tape:
      interval: 7
    T2_US_Purdue:
      interval: 7
    T2_BR_UERJ:
      interval: 7
    T1_ES_PIC_Disk:
      interval: 7
    T1_UK_RAL_Tape:
      interval: 0
      maxdarkfraction: "0.0000001"
    T1_US_FNAL_Disk:
      interval: 7
    T2_TW_NCHC:
      interval: 7
    #T2_UK_London_IC_Test:
    #  server: gfe02.grid.hep.ph.ic.ac.uk:1095
    #  interval: 1
    T2_ES_CIEMAT:
      interval: 7
    #T2_PT_NCG_Lisbon_Test:
    #  server: xroot-data02.ncg.ingrid.pt:1094
    #  interval: 1
    T2_UK_SGrid_Bristol:
      interval: 7
    T2_DE_RWTH:
      interval: 7
    #T2_HU_Budapest_Test:
    #  server: grid143.kfki.hu:11000
    #  interval: 1
    #T2_BR_SPRACE_Test:
    #  server: xrd-ds06.sprace.org.br:1094
    #  interval: 1
    T2_RU_IHEP:
      interval: 7
    #T2_TR_METU_Test:
    #  server: eymir.grid.metu.edu.tr:11001
    #  interval: 1
    #T2_US_UCSD_Test:
    #  server: gftp-1.t2.ucsd.edu:1094
    #  interval: 1
    T2_IT_Bari:
      interval: 7
    T2_RU_JINR:
      interval: 7
    T2_IT_Pisa:
      interval: 7
    T2_FI_HIP:
      interval: 7
    T2_IT_Legnaro:
      interval: 7
    #T3_TW_NTU_HEP_Test:
    #  server: ntugrid6.phys.ntu.edu.tw:11000
    #  interval: 1
    T2_BE_IIHE:
      interval: 7
    T2_PL_Swierk:
      interval: 7
    #T2_EE_Estonia_Test:
    #server: [2001:bb8:4004:ff:d::3]:1094
    #interval: 1
    T2_UK_SGrid_RALPP:
      interval: 7
    T2_US_Wisconsin:
      interval: 7
    #T2_CN_Beijing_Test:
    #  server: seadmin.ihep.ac.cn:1094
    #  interval: 1
    #T2_US_Caltech_Test:
    #  #server: transfer-9.ultralight.org:1095
    #  server: transfer-1.ultralight.org:1095
    #  interval: 1
    #T2_US_Florida_Test:
    #  server: cmsio5.rc.ufl.edu:1094
    #  #server: cmsio7.rc.ufl.edu:1094
    #  interval: 1
    T2_IT_Rome:
      interval: 7
    #T2_GR_Ioannina_Test:
    #  server: grid02.physics.uoi.gr:11001
    #  interval: 1
    T2_PK_NCP:
      interval: 7
    #T3_CH_PSI_Test:
    #  server: t3se01.psi.ch
    #  #server: t3se01.psi.ch:1095
    #  interval: 1
    #T2_UK_London_Brunel_Test:
    #  server: dc2-grid-64.brunel.ac.uk
    #  #server: dc2-grid-64.brunel.ac.uk:11001
    #  interval: 1
    #T2_BE_UCL_Test:
    #  server: ingrid-se04.cism.ucl.ac.be:1094
    #  interval: 1
    #T2_US_Vanderbilt_Test:
    #  server: xrootd.accre.vanderbilt.edu
    #  #server: xrootd-srv.accre.vanderbilt.edu:1094
    #  interval: 1
    T2_RU_INR:
      interval: 7
    #T2_RU_ITEP_Test:
    #  server: se3.itep.ru:1095
    #  interval: 1
    T2_IN_TIFR:
      interval: 7
    T2_CH_CSCS:
      interval: 7
    T2_FR_IPHC:
      interval: 7
    T2_AT_Vienna:
      interval: 7
    #T2_ES_IFCA_Test:
    #  server: pool04.ifca.es:1094
    #  interval: 1
    #T3_IT_Trieste_Test:
    #  server: cmsxrd.ts.infn.it:1094
    #  interval: 1
    #T3_US_Baylor_Test:
    #  server: kodiak-se.baylor.edu:1094
    #  interval: 1
    #T2_CH_CERN_Test:
    #  #server: eoscms-qdb-250e2da131.cern.ch:1098
    #  server: eoscms.cern.ch:1094
    #  interval: 1
    T2_KR_KISTI:
      interval: 7
    #T2_UA_KIPT_Test:
    #  server: cms-se0.kipt.kharkov.ua:11001
    #  interval: 1
    #T3_US_UMD_Test:
    #  server: hepcms-0.umd.edu:1094
    #  interval: 1
    #T2_US_MIT_Test:
    #  server: t3serv006.mit.edu
    #  #server: xrootd9.cmsaf.mit.edu:1094
    #  interval: 1
    #T2_KR_KNU_Test:
    #  server: xrootd.knu.ac.kr:1095
    #  interval: 1
    #T3_US_Colorado_Test:
    #  server: hepxrd01.colorado.edu:1094
    #  interval: 1
    #T2_DE_DESY_Test:
    #  server: t2-cms-xrootd03.desy.de:1094
    #  interval: 1
    #T2_US_Nebraska_Test:
    #  server: red-gridftp10.unl.edu:1094
    #  interval: 1
    #T2_TW_NCHC_Test:
    #  server: se01.grid.nchc.org.tw:11001
    #  interval: 1
    T3_US_Rutgers:
      interval: 7
    T1_IT_CNAF_Disk:
      interval: 7
    T2_BR_SPRACE:
      interval: 7
    T2_CN_Beijing:
      interval: 7
    T2_DE_DESY:
      interval: 7
    T2_EE_Estonia:
      interval: 7
    T2_HU_Budapest:
      interval: 7
    T2_PT_NCG_Lisbon:
      interval: 7
    T2_TR_METU:
      interval: 7
    T2_UA_KIPT:
      interval: 7
    T2_UK_London_Brunel:
      interval: 7
    T2_US_Caltech:
      interval: 7
    T2_US_Florida:
      interval: 7
    T2_US_MIT:
      interval: 7
    T2_US_Nebraska:
      interval: 7
    T2_US_UCSD:
      interval: 7
    T2_US_Vanderbilt:
      interval: 7
    T2_CH_CERN:
      interval: 7
    T0_CH_CERN_Disk:
      interval: 7
    #T1_FR_CCIN2P3_Tape:
    #   server: ccxrootdcms.in2p3.fr:1094
    #   server_root: /pnfs/in2p3.fr/data/cms/data
    #   interval: 7
    T1_FR_CCIN2P3_Disk:
     interval: 7
    T1_RU_JINR_Disk:
      interval: 7
    T2_BE_UCL:
      interval: 7
    T2_ES_IFCA:
      interval: 7
    T2_RU_ITEP:
      interval: 7
    T2_UK_London_IC:
      interval: 7
    T3_KR_UOS:
      interval: 7
    T2_PL_Cyfronet:
      interval: 7
    T3_US_Colorado:
      interval: 7
    T2_LB_HPC4L:
      interval: 7
