consistency:
  instance: "prod"
  defaultRoot: "/"
  schema: "CMS_RUCIO_PROD"
reportStorageClass:
  osShareID: f704fcbe-a909-4467-95b9-19661c1d4e66
  osShareAccessID: 38a148e3-5377-4878-9ac0-e3a95c816684
image:
  repository: registry.cern.ch/cmsrucio/rucio-consistency
<<<<<<< HEAD
  tag: release-4.0.2
=======
  tag: release-4.0.3
>>>>>>> 9df7f07 (Version bump for CE config fix)
