image:
  tag: release-37.1.0

ingress:
  enabled: true
  hosts:
    - "cms-rucio-newui.cern.ch"

# Is this still needed?
proxy:
  rucioProxy: "cms-rucio.cern.ch"
  rucioAuthProxy: "cms-rucio-auth.cern.ch:443"

config:
  webui:
    # hostname of the rucio server, include http:// or https://
    rucio_host: "https://cms-rucio.cern.ch"
    # hostname of the rucio-auth server, include http:// or https://
    rucio_auth_host: "https://cms-rucio-auth.cern.ch"
    # hostname of the webui ( without http:// or https://, just the hostname, no port or scheme required)
    hostname: "cms-rucio-newui.cern.ch"
    project_url: "https://rucio.cern.ch"
    server_ca_bundle: "/etc/grid-security/CERN-bundle.pem"
