# Controls the release of all the compenents except the new WebUI which follows a different timetable
image:
  tag: release-40.3.0.cms1

# Always set the FTS renewal release the same unless there are issues
ftsRenewal:
  image:
    tag: 40.3.0

# Here because it's needed for all the different components
config:
  database:
    schema: "CMS_RUCIO_PROD"
