# More reapers (or threads) than this cause issues for CERN Oracle, so use only temporarily. Reducing the sleep time is similar
reaperCount: 8
judgeInjectorCount: 2
judgeRepairerCount: 2
conveyorTransferSubmitterCount: 8
conveyorPollerCount: 4
conveyorReceiverCount: 2
conveyorFinisherCount: 4
conveyorThrottlerCount: 1

judgeEvaluatorCount: 2
tracerKronosCount: 3
judgeCleanerCount: 2
replicaRecovererCount: 1
minosTemporaryExpirationCount: 1

replicaRecoverer:
  activeMode: true
  limitSuspiciousFilesOnRse: 500
  secretMounts:
    - secretFullName: replica-recoverer-config
      mountPath: /opt/rucio/etc/suspicious_replica_recoverer.json
      subPath: suspicious_replica_recoverer.json
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 400Mi

reaper:
  threads: 4
  includeRses: "reaper=True\\rse_type=TAPE\\tier=1\\tier=0\\T2_CH_CERN"
  chunkSize: 4000
  sleepTime: 120
  config:
    common:
      loglevel: "DEBUG"

conveyorPoller:
  threads: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1000Mi
    requests:
      cpu: 750m
      memory: 400Mi

conveyorTransferSubmitter:
  groupBulk: 200
  bulk: 400
  sleepTime: 60
  threads: 5
  sourceStrategy: throughput

judgeEvaluator:
  threads: 8
  didLimit: 1000
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 200Mi

judgeRepairer:
  threads: 2
judgeInjector:
  threads: 3

conveyorFinisher:
  threads: 5
  resources:
    limits:
      memory: 8000Mi
    requests:
      memory: 600Mi

podLabels:
  rucioInstance: "prod"

transmogrifier:
  threads: 8
  sleepTime: 30
  bulk: 400

tracerKronos:
  threads: 2
  sleepTimeFiles: 120
  sleepTimeDatasets: 30

config:
  common:
    loglevel: "INFO"
  messaging_hermes:
    port: "61313"
    nonssl_port: "61313"
  tracer_kronos:
    chunksize: "5"
    prefetch_size: "5"
