loadtest:
  rucioHome: "/opt/rucio-prod/"
  proxySecret: "server-rucio-x509up"
  sourceExpression: "loadtest=True"
  destinationExpression: "loadtest=True"

image:
  repository: registry.cern.ch/cmsrucio/rucio-loadtest-client
  pullPolicy: Always
  tag: "1.0.5"

persistentVolumes:
  grid-cern-ch:
    name: csi-cvmfs-grid-pvc
    mountPath: /cvmfs/grid.cern.ch

resources:
  limits:
    cpu: 200m
    memory: 1Gi
