consistency:
  instance: "prod"
  defaultRoot: "/"
  schema: "CMS_RUCIO_PROD"
  prometheus_servers: "prometheus-prometheus-pushgateway.prometheus:9091"
  prometheus_prefix: "rucio.prod.cc"
  rucio_host: "http://cms-rucio.cern.ch"
  auth_host: "https://cms-rucio-auth.cern.ch"
  auth_type: "x509_proxy"
  ca_cert: "/etc/grid-security/certificates/"
  request_retries: "3"
reportStorageClass:
  osShareID: f704fcbe-a909-4467-95b9-19661c1d4e66
  osShareAccessID: 38a148e3-5377-4878-9ac0-e3a95c816684
image:
  repository: registry.cern.ch/cmsrucio/rucio-consistency
  tag: release-4.7.1
resources:
  requests:
    memory: 6000Mi
    cpu: 4000m
