replicaCount: 1

ingress:
  hosts:
    - "cms-rucio-webui.cern.ch"

# Is this still needed?
proxy:
  rucioProxy: "cms-rucio.cern.ch"
  rucioAuthProxy: "cms-rucio-auth.cern.ch:443"

config:
  react:
    rucioHost: "cms-rucio.cern.ch"
    rucioAuthHost: "cms-rucio-auth.cern.ch:443"

httpd_config:
  legacy_dn: "True"
  rucio_hostname: "cms-rucio-webui.cern.ch"
