apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-traces
spec:
  releaseName: traces
  chart:
    spec:
      chart: helm/rucio-traces
      sourceRef:
        kind: HelmRepository
        name: cms-rucio-oci
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-traces
    - kind: ConfigMap
      name: instance-traces
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: wmagentBroker.stompPassword
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: cmsswPopBroker.stompPassword
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: xrootdBroker.stompPassword
