apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-eagle-values
  namespace: kube-eagle
data:
  values.yaml: |+
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      tls: []
