apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-eagle
spec:
  releaseName: kube-eagle
  chart:
    spec:
      chart: kube-eagle
      sourceRef:
        kind: HelmRepository
        name: kube-eagle
        namespace: flux-system
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: cms-eagle-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: instance-eagle-values
      valuesKey: values.yaml
  install:
    remediation:
      retries: 3
