replicaCount: 1
ingress:
  hosts: 
    - cms-rucio-int.cern.ch

config:
  conveyor:
    use_preparer: "True"
  oidc:
    idpsecrets: "/opt/rucio/etc/idpsecrets.json"
    admin_issuer: "cms"
    expected_audience: "rucio"

additionalSecrets:
  idpsecrets:
    secretName: idpsecrets
    mountPath: /opt/rucio/etc/
    subPaths:
      - idpsecrets.json

optional_config:
  SQLALCHEMY_WARN_20: 1
  PYTHONWARNINGS: "always::DeprecationWarning"

ftsRenewal:
  schedule: "30 */12 * * *"
