apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - ../base
  - ../base/rucio-daemons
  - ../base/rucio-server
  - ../base/rucio-authserver
  - ../base/rucio-traceserver
  - ../base/rucio-webui
  - ../base/rucio-probes
  - ../base/cms-rucio-cron
  - ../base/cms-rucio-cvmfs
  - ../options/globus-daemons
  - ../base/rucio-newui
  - ../base/rucio-int-newui
  - ../base/patches
  - ../base/configs

configMapGenerator:
  - name: instance-rucio-server
    files:
      - values.yaml=int-rucio-server.yaml
  - name: instance-rucio-authserver
    files:
      - values.yaml=int-rucio-authserver.yaml
  - name: instance-rucio-traceserver
    files:
      - values.yaml=int-rucio-traceserver.yaml
  - name: instance-rucio-daemons
    files:
      - values.yaml=int-rucio-daemons.yaml
  - name: instance-rucio-webui
    files:
      - values.yaml=int-rucio-webui.yaml
  - name: instance-rucio-newui
    files:
      - values.yaml=int-rucio-newui.yaml
  - name: instance-rucio-int-newui
    files:
      - values.yaml=int-rucio-int-newui.yaml
  - name: instance-rucio-probes
    files:
      - values.yaml=int-rucio-probes.yaml
  - name: instance-rucio-release
    files:
      - values.yaml=int-release.yaml
  - name: instance-consistency
    files:
      - values.yaml=int-consistency.yaml
  - name: instance-consistency-jobs
    files:
      - values.yaml=int-consistency-jobs.yaml
  - name: instance-rucio-cron
    files:
      - values.yaml=int-cms-cron.yaml
  - name: globus-rucio-daemons
    files:
      - values.yaml=int-globus-daemons.yaml
configurations:
  - kustomizeconfig.yaml
