apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
secretGenerator:
  - name: replica-recoverer-config
    options:
      disableNameSuffixHash: true
    files:
      -  suspicious_replica_recoverer.json
