# Rahul 4 is needed for Rucio 35 series
# 7308 is the equivalent for Rucio 36. Can get rid of Rahul 4 on upgrade

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
secretGenerator:
  - name: replica-recoverer-config
    options:
      disableNameSuffixHash: true
    files:
      -  suspicious_replica_recoverer.json
