envFrom:
  - secretRef:
      name: opensearch-creds

logLevel: debug

## Mounting /etc/machine-id with FileOrCreate
daemonSetVolumes:
- name: varlog
  hostPath:
    path: /var/log
- name: etcmachineid
  hostPath:
    path: /etc/machine-id
    type: FileOrCreate
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers
    type: DirectoryOrCreate

config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*_rucio_*.log
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

        
  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    # [OUTPUT]
    #     Name stdout
    #     Match kube.*
    #     Format json_lines

    [OUTPUT]
        Name opensearch
        Match kube.*
        Host ${opensearchHost}
        Port ${opensearchPort}
        Path ${opensearchPath}
        HTTP_Passwd ${opensearchPassword}
        HTTP_User ${opensearchUser}
        Logstash_Format On
        Logstash_Prefix test-rucio-int
        Logstash_DateFormat %Y-%m-%d
        Retry_Limit False
        Trace_Output On
        Trace_Error On
        tls On
        tls.debug 4
        tls.verify Off
        Suppress_Type_Name On
