apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentbit
resources:
  - namespace.yaml
  - release.yaml

configMapGenerator:
  - name: instance-fluentbit-values
    files:
      - values.yaml=cm-cms-fluentbit.yaml
