apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  releaseName: fluent-bit
  chart:
    spec:
      chart: fluent-bit
      version: ">=0.40.0 <0.41.0"
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: flux-system

  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: instance-fluentbit-values
      valuesKey: values.yaml
  install:
    remediation:
      retries: 3
