#Secret containing HTTP_Username and HTTP_Passwd for the ES output

apiVersion: v1
kind: Secret
metadata:
  name: fluentbit-es
  namespace: fluentbit
type: Opaque
data:
  HTTP_Username: dGVzdAo=
  HTTP_Passwd: VGl0aHt3cnVtRWlrT2Fkb25Cb3RDdXRoKgo=
