apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-daemons
spec:
  releaseName: daemons
  chart:
    spec:
      chart: rucio-daemons
      version: ">=32.0 <33.0"
      sourceRef:
        kind: HelmRepository
        name: rucio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-rucio-common
    - kind: ConfigMap
      name: cms-rucio-daemons
    - kind: ConfigMap
      name: instance-rucio-daemons
    - kind: ConfigMap
      name: instance-rucio-release
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default
    - kind: Secret
      name: rucio-secrets
      valuesKey: hermes_password
      targetPath: config.messaging_hermes.password
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: config.tracer_kronos.password
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: config.messaging_cache.password
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: config.trace.password
    - kind: Secret
      name: rucio-secrets
      valuesKey: kronos_password
      targetPath: config.messaging_fts3.password
    - kind: Secret
      name: rucio-secrets
      valuesKey: gitlab_token
      targetPath: config.cms.gitlab
    - kind: Secret
      name: rucio-secrets
      valuesKey: monit_token
      targetPath: config.cms.monit
    - kind: Secret
      name: rucio-secrets
      valuesKey: globus_client
      targetPath: optional_config.rucio_cfg_cms_globus_client
    - kind: Secret
      name: rucio-secrets
      valuesKey: globus_refresh
      targetPath: optional_config.rucio_cfg_cms_globus_refresh
